#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < rounded-corners-20200402-0e158c5.diff

meson \
    --prefix=/usr \
    -Ddbus=false \
    -Dregex=false \
    . build

ninja -C build
ninja -C build install
