#!/bin/sh -e

patch -p1 < /usr/share/doc/kiss/wiki/kernel/no-perl.patch
patch -p1 < bashless.patch

sed '/<stdlib.h>/a #include <linux/stddef.h>' \
    tools/objtool/arch/x86/decode.c > _
mv -f _ tools/objtool/arch/x86/decode.c

make olddefconfig
make -j"$(nproc)"
make INSTALL_MOD_PATH="$1/usr" INSTALL_MOD_STRIP=1 modules_install

rm "$1/usr/lib/modules/$2/build" "$1/usr/lib/modules/$2/source"

install -Dm644 "arch/x86/boot/bzImage" "$1/boot/EFI/Kiss/vmlinuz.efi"
install -Dm644 "System.map"            "$1/boot/System.map"