#!/bin/sh

mount /dev/sdb2 "/boot/efi/"
rm -rf "/boot/System.map-*" "/boot/efi/EFI/Kiss/vmlinuz-*"
mv "/boot/System.map" "/boot/System.map-5.4.28"
mv "/boot/vmlinuz" "/boot/efi/EFI/Kiss/vmlinuz-5.4.28.efi"
umount "/boot/efi"
