#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    -Dudev=false \
    -Damdgpu=false \
    -Dexynos=false \
    -Dfreedreno=false \
    -Dintel=true \
    -Dnouveau=false \
    -Domap=false \
    -Dradeon=false \
    -Dtegra=false \
    -Dvc4=false \
    -Detnaviv=false \
    -Dvmwgfx=false \
    -Dlibkms=true \
    -Dvalgrind=false \
    . build

ninja -C build
ninja -C build install
