#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    -Dvalgrind=false \
    -Dintel=false \
    -Dnouveau=false \
    -Dradeon=false \
    -Dvmwgfx=false \
    -Dman-pages=false \
    -Damdgpu=true \
    . build

ninja -C build
ninja -C build install
