#!/bin/sh -e

./configure \
    --prefix='/usr' \
    --sysconfdir='/etc' \
    --enable-udev \
    --enable-networking \
    --enable-sse \
    --enable-threads \
    --disable-jack \
    --disable-oss \
    --disable-discord

make
make DESTDIR="$1" install
