#!/bin/sh -e

./configure \
    --prefix='/usr' \
    --enable-dynamic \
    --disable-vg \
    --disable-discord \
    --disable-builtinminiupnpc \
    --disable-builtinmbedtls \
    --disable-builtinflac \
    --disable-builtinzlib \
    --disable-jack \
    --disable-oss \
    --disable-discord
make clean
make
make -C gfx/video_filters
make DESTDIR="$1" install
