#!/bin/sh -e

install -Dm644 amd/amd_sev_fam17h_model0xh.sbin   -t "$1/usr/lib/firmware/amd"
install -Dm644 amd-ucode/microcode_amd_fam17h.bin -t "$1/usr/lib/firmware/amd-ucode"
install -Dm644 amdgpu/polaris10_*                 -t "$1/usr/lib/firmware/amdgpu"
install -Dm644 rtl_nic/rtl8168g-2.fw              -t "$1/usr/lib/firmware/rtl_nic"
