#!/bin/sh -e

cd src

make
make DESTDIR="$1" EXDIR="$1/usr/bin" LIBDIR="$1/usr/lib" MANDIR="$1/usr/man" PREFIX=/usr install

#mv -f "$1/usr/local/bin" "$1/usr/bin"
#mv -f "$1/usr/local/share" "$1/usr/share"
